version: "3.9"

services:
  mysql:
    container_name: stock_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "stock"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - stock-db-data:/var/lib/mysql/

volumes:
  stock-db-data:
