version: "3"

services:
    mysql:
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: stock
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - mysql_data_container:/var/lib/mysql
    redis:
        image: docker.io/bitnami/redis:6.2
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'

volumes:
    mysql_data_container:
    redis_data:
        driver: local
