from tasks.sync_stocks import sync_stocks
from tasks.sync_kline import sync_kline_day_all, sync_kline_by_code
from tasks.training_model import training_model
from tasks.generate_report import generate_report
from tasks.sync_index_kline import sync_index_kline_by_code, sync_index_kline_day_all
